name: trabajo_fin_grado
description: "Trabajo de Fin de Grado de Daniel Montealegre Claramonte"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-43.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.2
  audioplayers: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/img/std/
    - assets/img/mts/
    - assets/json/
    - assets/sfx/
